// Pool of visual identifiers handed out to boxes, one at a time, in a shuffled
// order fixed at seed time. Each entry needs a glyph that is recognizable at a
// glance from across a room and distinct from every other glyph in the list.
//
// RESERVED is held back from the draw and belongs permanently to the default
// box. Its glyph must not appear in POOL.

export const RESERVED = { name: 'Not in Storage', glyph: '\u{1F3E0}' };

export const POOL = [
  { name: 'Dog', glyph: '\u{1F436}' },
  { name: 'Cat', glyph: '\u{1F431}' },
  { name: 'Mouse', glyph: '\u{1F42D}' },
  { name: 'Hamster', glyph: '\u{1F439}' },
  { name: 'Rabbit', glyph: '\u{1F430}' },
  { name: 'Fox', glyph: '\u{1F98A}' },
  { name: 'Bear', glyph: '\u{1F43B}' },
  { name: 'Panda', glyph: '\u{1F43C}' },
  { name: 'Koala', glyph: '\u{1F428}' },
  { name: 'Tiger', glyph: '\u{1F42F}' },
  { name: 'Lion', glyph: '\u{1F981}' },
  { name: 'Cow', glyph: '\u{1F42E}' },
  { name: 'Pig', glyph: '\u{1F437}' },
  { name: 'Frog', glyph: '\u{1F438}' },
  { name: 'Monkey', glyph: '\u{1F435}' },
  { name: 'Chicken', glyph: '\u{1F414}' },
  { name: 'Penguin', glyph: '\u{1F427}' },
  { name: 'Bird', glyph: '\u{1F426}' },
  { name: 'Chick', glyph: '\u{1F424}' },
  { name: 'Duck', glyph: '\u{1F986}' },
  { name: 'Eagle', glyph: '\u{1F985}' },
  { name: 'Owl', glyph: '\u{1F989}' },
  { name: 'Bat', glyph: '\u{1F987}' },
  { name: 'Wolf', glyph: '\u{1F43A}' },
  { name: 'Boar', glyph: '\u{1F417}' },
  { name: 'Horse', glyph: '\u{1F434}' },
  { name: 'Unicorn', glyph: '\u{1F984}' },
  { name: 'Bee', glyph: '\u{1F41D}' },
  { name: 'Caterpillar', glyph: '\u{1F41B}' },
  { name: 'Butterfly', glyph: '\u{1F98B}' },
  { name: 'Snail', glyph: '\u{1F40C}' },
  { name: 'Ladybug', glyph: '\u{1F41E}' },
  { name: 'Ant', glyph: '\u{1F41C}' },
  { name: 'Cricket', glyph: '\u{1F997}' },
  { name: 'Spider', glyph: '\u{1F577}\u{FE0F}' },
  { name: 'Scorpion', glyph: '\u{1F982}' },
  { name: 'Turtle', glyph: '\u{1F422}' },
  { name: 'Snake', glyph: '\u{1F40D}' },
  { name: 'Lizard', glyph: '\u{1F98E}' },
  { name: 'Rex', glyph: '\u{1F996}' },
  { name: 'Brontosaurus', glyph: '\u{1F995}' },
  { name: 'Octopus', glyph: '\u{1F419}' },
  { name: 'Squid', glyph: '\u{1F991}' },
  { name: 'Shrimp', glyph: '\u{1F990}' },
  { name: 'Crab', glyph: '\u{1F980}' },
  { name: 'Pufferfish', glyph: '\u{1F421}' },
  { name: 'Angelfish', glyph: '\u{1F420}' },
  { name: 'Fish', glyph: '\u{1F41F}' },
  { name: 'Dolphin', glyph: '\u{1F42C}' },
  { name: 'Whale', glyph: '\u{1F433}' },
  { name: 'Shark', glyph: '\u{1F988}' },
  { name: 'Crocodile', glyph: '\u{1F40A}' },
  { name: 'Cheetah', glyph: '\u{1F406}' },
  { name: 'Zebra', glyph: '\u{1F993}' },
  { name: 'Gorilla', glyph: '\u{1F98D}' },
  { name: 'Orangutan', glyph: '\u{1F9A7}' },
  { name: 'Elephant', glyph: '\u{1F418}' },
  { name: 'Hippo', glyph: '\u{1F99B}' },
  { name: 'Rhino', glyph: '\u{1F98F}' },
  { name: 'Camel', glyph: '\u{1F42A}' },
  { name: 'Giraffe', glyph: '\u{1F992}' },
  { name: 'Kangaroo', glyph: '\u{1F998}' },
  { name: 'Buffalo', glyph: '\u{1F403}' },
  { name: 'Goat', glyph: '\u{1F410}' },
  { name: 'Sheep', glyph: '\u{1F411}' },
  { name: 'Deer', glyph: '\u{1F98C}' },
  { name: 'Rooster', glyph: '\u{1F413}' },
  { name: 'Turkey', glyph: '\u{1F983}' },
  { name: 'Peacock', glyph: '\u{1F99A}' },
  { name: 'Parrot', glyph: '\u{1F99C}' },
  { name: 'Swan', glyph: '\u{1F9A2}' },
  { name: 'Flamingo', glyph: '\u{1F9A9}' },
  { name: 'Dove', glyph: '\u{1F54A}\u{FE0F}' },
  { name: 'Badger', glyph: '\u{1F9A1}' },
  { name: 'Otter', glyph: '\u{1F9A6}' },
  { name: 'Sloth', glyph: '\u{1F9A5}' },
  { name: 'Skunk', glyph: '\u{1F9A8}' },
  { name: 'Hedgehog', glyph: '\u{1F994}' },
  { name: 'Beaver', glyph: '\u{1F9AB}' },
  { name: 'Squirrel', glyph: '\u{1F43F}\u{FE0F}' },
  { name: 'Seal', glyph: '\u{1F9AD}' },
  { name: 'Ram', glyph: '\u{1F40F}' },
  { name: 'Ox', glyph: '\u{1F402}' },
  { name: 'Llama', glyph: '\u{1F999}' },
  { name: 'Poodle', glyph: '\u{1F429}' },
  { name: 'Dodo', glyph: '\u{1F9A4}' },
  { name: 'Beetle', glyph: '\u{1FAB2}' },
  { name: 'Cockroach', glyph: '\u{1FAB3}' },
  { name: 'Fly', glyph: '\u{1FAB0}' },
  { name: 'Worm', glyph: '\u{1FAB1}' },
  { name: 'Mosquito', glyph: '\u{1F99F}' },
  { name: 'Lobster', glyph: '\u{1F99E}' },
  { name: 'Mammoth', glyph: '\u{1F9A3}' },
  { name: 'Bison', glyph: '\u{1F9AC}' },
  { name: 'Dragon', glyph: '\u{1F409}' },
  { name: 'Raccoon', glyph: '\u{1F99D}' },
  { name: 'Rat', glyph: '\u{1F400}' },
  { name: 'Chimp', glyph: '\u{1F412}' },
  { name: 'Hound', glyph: '\u{1F415}' },
  { name: 'Jackrabbit', glyph: '\u{1F407}' },
];
